// ERRORS
const OBJECT_NOT_FOUND_ERR = `Object not found`;

// BOOTCAMP MODEL
const BOOTCAMP_NAME_REQ_VALIDATION = 'Please add a name';
const BOOTCAMP_NAME_MAXLN_VALIDATION =
  'Name can not be more than 50 characters';
const BOOTCAMP_DESCRIPTION_REQ_VALIDATION = 'Please add a description';
const BOOTCAMP_DESCRIPTION_MAXLN_VALIDATION =
  'Description can not be more than 50 characters';
const BOOTCAMP_WEBSITE_MATCH_VALIDATION =
  'Please use a valid URL with HTTP or HTTPS';
const BOOTCAMP_PHONE_MAXLN_VALIDATION =
  'Phone number can not be longer than 20 characters';
const BOOTCAMP_EMAIL_MATCH_VALIDATION = 'Please add a valid email';
const BOOTCAMP_ADDRESS_REQ_VALIDATION = 'Please add an address';
const BOOTCAMP_AVG_RATING_MIN_VALIDATION = 'Rating must be at least 1';
const BOOTCAMP_AVG_RATING_MAX_VALIDATION =
  'Rating must can not be more than 10';

// COURSE MODEL
const COURSE_TITLE_REQ_VALIDATION = 'Please add a course title';
const COURSE_DESCRIPTION_REQ_VALIDATION = 'Please add a description';
const COURSE_WEEKS_REQ_VALIDATION = 'Please add number of weeks';
const COURSE_TUITION_REQ_VALIDATION = 'Please add a tuition cost';
const COURSE_MIN_SKILL_REQ_VALIDATION = 'Please add a minimum skill';

//USER MODEL
const USER_NAME_REQ_VALIDATION = 'Please add a name';
const USER_EMAIL_REQ_VALIDATION = 'Please add a email';
const USER_EMAIL_MATCH_VALIDATION = 'Please add a valid email';
const USER_PASSWORD_REQ_VALIDATION = 'Please add a password';

module.exports = {
  OBJECT_NOT_FOUND_ERR,
  BOOTCAMP_NAME_REQ_VALIDATION,
  BOOTCAMP_NAME_MAXLN_VALIDATION,
  BOOTCAMP_DESCRIPTION_REQ_VALIDATION,
  BOOTCAMP_DESCRIPTION_MAXLN_VALIDATION,
  BOOTCAMP_PHONE_MAXLN_VALIDATION,
  BOOTCAMP_EMAIL_MATCH_VALIDATION,
  BOOTCAMP_ADDRESS_REQ_VALIDATION,
  BOOTCAMP_AVG_RATING_MIN_VALIDATION,
  BOOTCAMP_AVG_RATING_MAX_VALIDATION,
  BOOTCAMP_WEBSITE_MATCH_VALIDATION,
  COURSE_TITLE_REQ_VALIDATION,
  COURSE_DESCRIPTION_REQ_VALIDATION,
  COURSE_WEEKS_REQ_VALIDATION,
  COURSE_TUITION_REQ_VALIDATION,
  COURSE_MIN_SKILL_REQ_VALIDATION,
  USER_NAME_REQ_VALIDATION,
  USER_EMAIL_REQ_VALIDATION,
  USER_EMAIL_MATCH_VALIDATION,
  USER_PASSWORD_REQ_VALIDATION,
};
